use_frameworks!
inhibit_all_warnings!
platform :ios, '11.0'

# Please use 'pod install --repo-update' to ensure you have the latest versions of our SDKs.

target 'AppLovin MAX Demo App - ObjC' do
  pod 'AppLovinSDK'
  pod 'Adjust'

  # Menta Global SDK and the local MAX custom adapter.
  pod 'MentaBaseGlobal', '1.0.33'
  pod 'MentaMediationGlobal', '1.0.33'
  pod 'MentaVlionGlobal', '1.0.33'
  pod 'MentaVlionGlobalAdapter', '1.0.33'
  pod 'MaxMentaAdapter', :path => '../Menta'
end
